name: XcraftMoneyReward
version: 1.2.2
author: INemesisI

main: de.xcraft.inemesisi.moneyreward.XcraftMoneyReward
load: POSTWORLD

depend: [XcraftLibrary, Vault]
softdepend: [Essentials]

commands:
  moneyreward:
    aliases: mr
    

permissions:
    XcraftMoneyReward.User:
        description: Access  to all Rewards
        children:
            XcraftMoneyReward.Daily: true
            XcraftMoneyReward.Online: true
            XcraftMoneyReward.Mob: true
        default: true

    XcraftMoneyReward.Daily:
        description: Reward for daily logins
        
    XcraftMoneyReward.Online:
        description: Regular reward for playing on the server
        
    XcraftMoneyReward.Mob:
        description: Reward for killing mobs
        
    XcraftMoneyReward.Mob.Camp.Exempt:
        description: Exemption for the Camp-Limit